### ISSUE TITLE
Download and Setup VirtualBox

### ISSUE THREAD

**Issue by yuriaru** [RutgersGRID/devops-git-actions#1]

**Comment by Voxelghiest** [comment]
Downloading and setting up VirtualBox was a bit of a hassle because I don't admin privileges on this computer. If you do it for yourself, make sure you do.

The [documentation](https://www.virtualbox.org/manual/ch02.html#installation-mac) Oracle has is pretty good, though, and should be able to guide you through the process. Once you install VirtualBox, the next step is to download the ISO for the OS you want to run.

**Comment by yuriaru** [comment]
This has been done on Hunter's computer and it is up and running.
